name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo run --release generate
      - run: cargo run --release measure
      - run: cargo run --release measure --mmap
      - run: cargo run --release sum
